# Generated by Django 3.1.5 on 2021-01-29 15:07

import accounting.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('credit', models.FloatField(default=0.0)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ClientCreditHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.IntegerField()),
                ('caster', models.IntegerField()),
                ('comment', models.TextField(default='')),
                ('type', models.IntegerField(choices=[(0, 'UNSET'), (1, 'USER_ENTERED'), (2, 'ORDER_CANCELATION'), (3, 'TICKET_CANCELATION'), (4, 'CREDIT_CONSUMED'), (5, 'REFUND'), (6, 'SYSTEM_OP'), (7, 'MIGRATION')], default=accounting.models.HistoryTypeEnum['UNSET'])),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_history', to='accounting.client')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
