# Generated by Django 3.1.5 on 2021-01-29 15:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import order.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientRefund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Paiement UPEM', max_length=128)),
                ('comment', models.TextField(default='')),
                ('type', models.IntegerField(choices=[(0, 'UNSET'), (1, 'OFFICE'), (2, 'DIR'), (3, 'ONLINE'), (4, 'MIGRATION'), (5, 'MIGRATION_DIR')], default=order.models.OrderTypeEnum['UNSET'])),
                ('reference', models.CharField(default='', max_length=128)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('caster', models.IntegerField(default=0)),
                ('payer', models.IntegerField(default=0)),
                ('amount', models.FloatField(default=0.0)),
                ('amount_refunded', models.FloatField(blank=True, default=0.0)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='OrderStock',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product', models.IntegerField()),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee', models.IntegerField(default=0)),
                ('product', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(choices=[(0, 'UNSET'), (1, 'RESERVED'), (2, 'COMPLETED'), (3, 'REPORTED'), (4, 'REFUNDED'), (5, 'CANCELED'), (6, 'WAITING')], default=order.models.StatusEnum['UNSET'])),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='order.ticket')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(choices=[(0, 'UNSET'), (1, 'RESERVED'), (2, 'COMPLETED'), (3, 'REPORTED'), (4, 'REFUNDED'), (5, 'CANCELED'), (6, 'WAITING')], default=order.models.StatusEnum['UNSET'])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='order.order')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OrderMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.IntegerField(choices=[(0, 'UNSET'), (1, 'CASH'), (2, 'CHECK'), (3, 'ONLINE'), (4, 'VRMT'), (5, 'CREDIT'), (6, 'PAYPAL'), (7, 'STRIPE'), (8, 'ONLINE_VADS')], default=order.models.MethodEnum['UNSET'])),
                ('reference', models.CharField(default='', max_length=128)),
                ('amount', models.FloatField(default=0.0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='ClientCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_last_mod', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='order.client')),
            ],
        ),
    ]
