# Generated by Django 3.1.5 on 2021-02-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_amount_refunded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='Paiement UPEEM', max_length=128),
        ),
    ]
