# Generated by Django 3.1.5 on 2021-02-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210210_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount_refunded',
        ),
    ]
