# Generated by Django 3.1.5 on 2021-02-12 14:04

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_amount_rcvd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderStock',
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.IntegerField(choices=[(0, 'UNSET'), (1, 'RESERVED'), (2, 'COMPLETED'), (3, 'REPORTED'), (4, 'REFUNDED'), (5, 'CANCELED'), (6, 'WAITING'), (7, 'CREDITED')], default=order.models.StatusEnum['UNSET']),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='status',
            field=models.IntegerField(choices=[(0, 'UNSET'), (1, 'RESERVED'), (2, 'COMPLETED'), (3, 'REPORTED'), (4, 'REFUNDED'), (5, 'CANCELED'), (6, 'WAITING'), (7, 'CREDITED')], default=order.models.StatusEnum['UNSET']),
        ),
    ]
