# Generated by Django 3.1.5 on 2021-03-19 14:58

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20210212_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.IntegerField(choices=[(0, 'UNSET'), (1, 'OFFICE'), (2, 'DIR'), (3, 'ONLINE'), (4, 'MIGRATION'), (5, 'MIGRATION_DIR'), (6, 'MANUAL')], default=order.models.OrderTypeEnum['UNSET']),
        ),
    ]
