# Generated by Django 3.1.5 on 2021-01-29 15:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import registration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CAF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.IntegerField(choices=[(0, 'UNSET'), (1, 'NE'), (2, 'Q2'), (3, 'Q1')], default=registration.models.ChildQuotient['NE'])),
                ('q2', models.IntegerField(choices=[(0, 'UNSET'), (1, 'NE'), (2, 'Q2'), (3, 'Q1')], default=registration.models.ChildQuotient['NE'])),
                ('recipent_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.IntegerField(default=0)),
                ('parent', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(default='', max_length=100)),
                ('classroom', models.IntegerField(choices=[(0, 'UNSET'), (1, 'STP'), (2, 'SP'), (3, 'SM'), (4, 'SG'), (5, 'CP'), (6, 'CE1'), (7, 'CE2'), (8, 'CM1'), (9, 'CM2'), (10, 'SIX')], default=registration.models.ChildClass['UNSET'])),
                ('agreement', models.BooleanField(default=False)),
                ('accueil_mati', models.BooleanField(default=False)),
                ('accueil_midi', models.BooleanField(default=False)),
                ('accueil_merc', models.BooleanField(default=False)),
                ('accueil_vacs', models.BooleanField(default=False)),
                ('insurance_policy', models.CharField(default=0, max_length=128)),
                ('insurance_society', models.CharField(default='', max_length=128)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_last_mod', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_verified', models.DateTimeField(blank=True, null=True)),
                ('child', models.IntegerField(default=0)),
                ('school_year', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-school_year'],
            },
        ),
        migrations.CreateModel(
            name='Sibling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('asthme', models.BooleanField(default=False)),
                ('allergy_food', models.BooleanField(default=False)),
                ('allergy_drug', models.BooleanField(default=False)),
                ('allergy_food_details', models.TextField(blank=True, default='')),
                ('allergy_drug_details', models.TextField(blank=True, default='')),
                ('pai', models.IntegerField(choices=[(0, 'UNSET'), (1, 'NO'), (2, 'YES'), (3, 'ONGOING')], default=registration.models.ChildPAI['NO'])),
                ('pai_details', models.TextField(blank=True, default='')),
                ('medical_treatment', models.BooleanField(default=False)),
                ('vaccine_up_to_date', models.BooleanField(default=False)),
                ('lunettes', models.BooleanField(default=False)),
                ('lentilles', models.BooleanField(default=False)),
                ('protheses_dentaire', models.BooleanField(default=False)),
                ('protheses_auditives', models.BooleanField(default=False)),
                ('autres_recommandations', models.TextField(blank=True, default='')),
                ('doctor_names', models.CharField(default='', max_length=128)),
                ('doctor_phones', models.CharField(default='', max_length=128)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='health', serialize=False, to='registration.record')),
            ],
        ),
        migrations.CreateModel(
            name='RecordAuthorizations',
            fields=[
                ('bath', models.BooleanField(default=False)),
                ('image', models.BooleanField(default=False)),
                ('sport', models.BooleanField(default=False)),
                ('transport', models.BooleanField(default=False)),
                ('medical_transport', models.BooleanField(default=False)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='authorizations', serialize=False, to='registration.record')),
            ],
        ),
        migrations.CreateModel(
            name='RecordDiseases',
            fields=[
                ('rubeole', models.BooleanField(default=False)),
                ('varicelle', models.BooleanField(default=False)),
                ('angine', models.BooleanField(default=False)),
                ('rhumatisme', models.BooleanField(default=False)),
                ('scarlatine', models.BooleanField(default=False)),
                ('coqueluche', models.BooleanField(default=False)),
                ('otite', models.BooleanField(default=False)),
                ('rougeole', models.BooleanField(default=False)),
                ('oreillons', models.BooleanField(default=False)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='diseases', serialize=False, to='registration.record')),
            ],
        ),
        migrations.CreateModel(
            name='SiblingIntels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotient_1', models.IntegerField(choices=[(0, 'UNSET'), (1, 'NE'), (2, 'Q2'), (3, 'Q1')], default=registration.models.ChildQuotient['NE'])),
                ('quotient_2', models.IntegerField(choices=[(0, 'UNSET'), (1, 'NE'), (2, 'Q2'), (3, 'Q1')], default=registration.models.ChildQuotient['NE'])),
                ('recipent_number', models.IntegerField(default=0)),
                ('school_year', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_last_mod', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_verified', models.DateTimeField(blank=True, null=True)),
                ('sibling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intels', to='registration.sibling')),
            ],
            options={
                'ordering': ['-school_year'],
            },
        ),
        migrations.CreateModel(
            name='SiblingChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.IntegerField(default=0)),
                ('sibling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='registration.sibling')),
            ],
        ),
        migrations.CreateModel(
            name='RecordResponsible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, default='', max_length=128)),
                ('first_name', models.CharField(blank=True, default='', max_length=128)),
                ('job', models.CharField(blank=True, default='', max_length=128)),
                ('gender', models.IntegerField(choices=[(0, 'UNSET'), (1, 'MALE'), (2, 'FEMALE'), (3, 'TUTOR')], default=registration.models.UserGenderEnum['UNSET'])),
                ('email', models.CharField(blank=True, default='', max_length=128)),
                ('phone_cell', models.CharField(blank=True, default='', max_length=128)),
                ('phone_home', models.CharField(blank=True, default='', max_length=128)),
                ('phone_pro', models.CharField(blank=True, default='', max_length=128)),
                ('address_zip', models.CharField(blank=True, default='', max_length=128)),
                ('address_city', models.CharField(blank=True, default='', max_length=128)),
                ('address_address1', models.CharField(blank=True, default='', max_length=128)),
                ('address_address2', models.CharField(blank=True, default='', max_length=128)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibles', to='registration.record')),
            ],
        ),
        migrations.CreateModel(
            name='RecordRecuperater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(blank=True, default='', max_length=128)),
                ('phones', models.CharField(blank=True, default='', max_length=128)),
                ('quality', models.CharField(blank=True, default='', max_length=128)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recuperaters', to='registration.record')),
            ],
        ),
    ]
