# Generated by Django 3.1.5 on 2021-01-29 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('slug', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(default='', max_length=128)),
                ('first_name', models.CharField(default='', max_length=128)),
                ('job', models.CharField(default='', max_length=128)),
                ('gender', models.IntegerField(choices=[(0, 'UNSET'), (1, 'MALE'), (2, 'FEMALE'), (3, 'TUTOR')], default=users.models.UserGenderEnum['UNSET'])),
                ('slug', models.CharField(default='', max_length=256)),
                ('dob', models.DateField(blank=True, null=True)),
                ('birthplace', models.CharField(default='', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_auto_password', models.BooleanField(default=False)),
                ('accept_newsletter', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_confirmed', models.DateTimeField(blank=True, null=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('online_id', models.IntegerField(default=0)),
                ('auth', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('roles', models.ManyToManyField(to='users.Role')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserPhones',
            fields=[
                ('phone_cell', models.CharField(default='', max_length=20)),
                ('phone_home', models.CharField(default='', max_length=20)),
                ('phone_pro', models.CharField(default='', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='phones', serialize=False, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False)),
                ('phone', models.CharField(default='', max_length=20)),
                ('phone_type', models.IntegerField(choices=[(1, 'MAIN'), (2, 'HOME'), (3, 'HOME_CELL'), (4, 'HOME_FAX'), (5, 'WORK'), (6, 'WORK_CELL'), (7, 'WORK_FAX'), (8, 'OTHER')], default=users.models.UserPhoneType['HOME'])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_phones', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False)),
                ('email', models.CharField(max_length=128)),
                ('email_type', models.IntegerField(choices=[(1, 'HOME'), (2, 'WORK'), (3, 'OTHER')], default=users.models.UserEmailType['HOME'])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False)),
                ('name', models.CharField(default='', max_length=128)),
                ('address_type', models.IntegerField(choices=[(1, 'HOME'), (2, 'WORK'), (3, 'OTHER')], default=users.models.UserAddressType['HOME'])),
                ('city', models.CharField(default='', max_length=128)),
                ('address1', models.CharField(default='', max_length=128)),
                ('address2', models.CharField(default='', max_length=128)),
                ('zip_code', models.CharField(default='', max_length=12)),
                ('country', models.CharField(default='Martinique', max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.user')),
            ],
        ),
    ]
