# Generated by Django 3.1.5 on 2021-01-29 15:07

from django.db import migrations, models
import django.db.models.deletion
import params.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('slug', models.CharField(default='', max_length=128)),
                ('description', models.CharField(default='', max_length=128)),
                ('order', models.IntegerField(default=0)),
                ('date', models.DateField(blank=True, null=True)),
                ('category', models.IntegerField(choices=[(0, 'UNSET'), (1, 'PERI'), (2, 'JANVIER'), (3, 'FEVRIER'), (4, 'MARS'), (5, 'AVRIL'), (6, 'MAI'), (7, 'JUIN'), (8, 'JUILLET'), (9, 'AOUT'), (10, 'SEPTEMBRE'), (11, 'OCTOBRE'), (12, 'NOVEMBRE'), (13, 'DECEMBRE'), (14, 'TOUSSAINT'), (15, 'NOEL'), (16, 'CARNAVAL'), (17, 'PAQUES'), (18, 'GRDS_VACANCES_JUILLET'), (19, 'GRDS_VACANCES_AOUT')], default=params.models.CategoryEnum['UNSET'])),
                ('subcategory', models.IntegerField(choices=[(0, 'UNSET'), (1, 'MINUS6'), (2, 'PLUS6')], default=params.models.SubCategoryEnum['UNSET'])),
                ('stock_max', models.IntegerField(default=0)),
                ('stock_current', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('price_q1', models.FloatField(default=0.0)),
                ('price_q2', models.FloatField(default=0.0)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['subcategory', 'date'],
            },
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_start'],
            },
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('max', models.IntegerField(default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='params.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='params.schoolyear'),
        ),
    ]
