# Generated by Django 3.1.5 on 2021-04-06 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['school_year', 'order', 'subcategory', 'date']},
        ),
    ]
