# Generated by Django 3.1.5 on 2021-01-29 15:11

from django.db import migrations, models
import django.utils.timezone
import payment_vads.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionVADS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('trans_id', models.CharField(max_length=20)),
                ('trans_date', models.CharField(default='', max_length=20)),
                ('trans_status', models.CharField(max_length=50)),
                ('cust_email', models.EmailField(max_length=254)),
                ('ext_info_1', models.TextField()),
                ('order_id', models.PositiveIntegerField(default=0)),
                ('order_status', models.IntegerField(choices=[(0, 'WAITING'), (10, 'INCORRECT_PAYLOAD'), (11, 'INCORRECT_AMOUNT'), (12, 'INCORRECT_PRODUCT'), (20, 'COMPLETED')], default=payment_vads.models.OrderStatusEnum['WAITING'])),
                ('order_message', models.TextField(default='')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
